apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-gitops-app
  annotations:
    kubectl.kubernetes.io/restartedAt: "2025-12-03T11:34:00Z"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-gitops-app
  template:
    metadata:
      labels:
        app: my-gitops-app
    spec:
      # This is the correct placement for imagePullSecrets, at the same level as 'containers'
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
      - name: app
        # Use the digest here, but remove the leading colon from @sha256:
        image: docker.io/ffckyou123/my-app:temp
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-gitops-app-svc
spec:
  type: NodePort
  selector:
    app: my-gitops-app
  ports:
    - port: 80